#ifndef MESSAGE_HPP
#define MESSAGE_HPP

#include <string>
using std::string;

enum TaskType
{
    TASK_TYPE_LOGIN_SECTION_1 = 1,
    TASK_TYPE_LOGIN_SECTION_1_RESPONSE_OK,
    TASK_TYPE_LOGIN_SECTION_1_RESPONSE_ERROR,
    TASK_TYPE_LOGIN_SECTION_2,
    TASK_TYPE_LOGIN_SECTION_2_RESPONSE_OK,
    TASK_TYPE_LOGIN_SECTION_2_RESPONSE_ERROR,
    TASK_TYPE_REGISTER_SECTION_1,
    TASK_TYPE_REGISTER_SECTION_1_RESPONSE_OK,
    TASK_TYPE_REGISTER_SECTION_1_RESPONSE_ERROR,
    TASK_TYPE_REGISTER_SECTION_2,
    TASK_TYPE_REGISTER_SECTION_2_RESPONSE_OK,
    TASK_TYPE_REGISTER_SECTION_2_RESPONSE_ERROR
};

struct TLV{
    int type;
    int length;
    char data[1024];
};

struct Packet{
    int type;
    int length;
    string message;
};

#endif